AWSTemplateFormatVersion: '2010-09-09'

Description: >-
  Create a stack for EC2 instance creation, where the user must inform the KeyPair, 
  select the security group within the security groups already created in the environment, 
  it will only be allowed to create instances and amis types available in the free tier, 
  within the following regions: sa-east-1, us-east-1 and us-weast-1, optionally the user
  can add a UserData at creation time, and it should output the public IP of the generated instance.

Parameters:
  InstanceType:
    Description: 'Tipos de instancias permitidas'
    Type: String
    Default: t2.micro
    AllowedValues: [t2.micro]
    ConstraintDescription: 'Somente o tipo t2.micro eh valido'

  KeyName:
    Description: 'Nome da KeyPair existente'
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: 'KeyPair valida'

  SecurityGroupsCreated:
    Description: 'Nome do Security Group existente'
    Type: AWS::EC2::SecurityGroup::GroupName
    ConstraintDescription: 'Security group valido'
  
  UserDataScript:
    Type: String
    Description: 'User data script'

  SSHLocation:
    Description: 'IP Origem da liberacao do SSH'
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: 'IP de liberacao valido'

Mappings:
  Regions:
    sa-east-1:
      "HVM64": "ami-05855ed85de7fbd77"
    us-east-1:
      "HVM64": "ami-02e136e904f3da870"
    us-weast-1:
      "HVM64": "ami-03ab7423a204da002"

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref 'InstanceType'
      UserData:
        Fn::Base64: !Ref 'UserDataScript'
      SecurityGroups:
        - !Ref 'InstanceSecurityGroup'
        - !Ref 'SecurityGroupsCreated'
      KeyName: !Ref 'KeyName'
      ImageId: !FindInMap 
        - Regions
        - !Ref 'AWS::Region'
        - HVM64
  
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Permite acesso via porta 22 - SSH"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref 'SSHLocation'

Outputs:
  InstanceId:
    Description: "ID da instancia criada"
    Value: !Ref 'EC2Instance'
  PublicDNS:
    Description: "DNS publico da instancia criada"
    Value: !GetAtt [EC2Instance, PublicDnsName] 
  PublicIP:
    Description: "IP publico da instancia criada"
    Value: !GetAtt [EC2Instance, PublicIp] 

