AWSTemplateFormatVersion: '2010-09-09'

Description: >-
  Create a stack to create security groups, where the user must inform the name,
  protocol, ports and IP for that SG.

Parameters:
    GroupName:
      Description: 'Nome do security group'
      Type: String
    GroupDescription:
      Description: 'Descricao do security group'
      Type: String
    Protocol:
      Type: String
      AllowedValues: [tcp, udp, icmp, icmpv6]
      ConstraintDescription: 'Digite um protocolo valido'
    ToPort: 
      Description: 'To'
      Type: Number
    FromPort: 
      Description: 'From'
      Type: Number
    IPLocation:
      Description: 'IP Origem da liberacao do protocolo'
      Type: String
      MinLength: 9
      MaxLength: 18
      Default: 0.0.0.0/0
      AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
      ConstraintDescription: 'IP de liberacao valido'
      
    
Resources:
  InstanceSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: !Ref 'GroupDescription'
        GroupName: !Ref 'GroupName'
        SecurityGroupIngress:
          - IpProtocol: !Ref 'Protocol'
            FromPort: !Ref 'FromPort'
            ToPort: !Ref 'ToPort'
            CidrIp: !Ref 'IPLocation'
